### PR TITLE
Minor modification understanding-cryptography.md

### PR DESCRIPTION
**Pull request by privacywarrior**
Added decryption key to Basic terminology.

Slightly modified Asymmetric-key encryption example.

Corrected asymmetric spelling.

### CODE REVIEW

**Comment by ghost** [comment]
Nice catch with that misspelt `asymmetric`. Yeah, the asymmetric-key encryption example is a bit less confusing now.

Defining decryption key doesn't work with
> Now, this is where it gets interesting. Public key cryptography utilizes **two** keys. One for encryption and one for decryption.

Defining decryption key is unnecessary, as it's either same as the encryption key, or a private key -- both of which are explained further in the tutorial.

Anyway, thanks a lot!

**Comment by privacywarrior** [comment]
You are probably right about decryption key, but now I am wondering if "encryption key" is correct al all.
Maybe it should be just "key":
Key = data used to convert that specific plaintext to that specific ciphertext or vice versa.

**Comment by ghost** [comment]
Maybe `(Encryption/Decryption) key`?

**Comment by privacywarrior** [comment]
If we refer to `plaintext` and `ciphertext`, probably `key` alone is fine.
`Encryption/decryption` are adjectives that depend on the circumstances.

I don't know if adding the adjectives at the beginning makes it clearer or more confusing for a newcomer.

**Comment by ghost** [comment]
Good point. A probably-clearer version `Key (sometimes encryption key and decryption key)` is just way too long. I'll change it to `Key`.

**Pull request merged**
